on:
  - push

name: Build and Deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
          
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: dotnet publish
        run: |
          dotnet publish src/Reddit2Kindle.Blazor -c Release -o Blazor
          dotnet publish src/Reddit2Kindle.Functions -c Release -o Functions

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: reddit2kindle-blazor
          package: 'Blazor'

      - name: Deploy functions
        uses: azure/functions-action@v1
        with:
          app-name: reddit2kindle-functions
          package: 'Functions'